
###########################################################################
# DEV DEBUG
###########################################################################

build_android_dev_debug:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: devDebug
    GRADLE_TASK: ":android:assembleDevDebug"
    ARTIFACT_DIRECTORY: android/build/outputs/apk/dev/debug

###########################################################################
# DEV RELEASE
###########################################################################

build_android_dev_release:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: devRelease
    GRADLE_TASK: ":android:assembleDevRelease"
    ARTIFACT_DIRECTORY: android/build/outputs/apk/dev/release

###########################################################################
# PROD DEBUG
###########################################################################

build_android_prod_debug:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: prodDebug
    GRADLE_TASK: ":android:assembleProdDebug"
    ARTIFACT_DIRECTORY: android/build/outputs/apk/prod/debug

###########################################################################
# PROD RELEASE
###########################################################################

build_android_prod_release:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: prodRelease
    GRADLE_TASK: ":android:assembleProdRelease"
    ARTIFACT_DIRECTORY: android/build/outputs/apk/prod/release
