
###########################################################################
# DEV DEBUG
###########################################################################

build_android_dev_debug:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: DevDebug
    GRADLE_TASK: ":android:assembleDevDebug"
    ARTIFACT_DIRECTORY: "android/build/outputs/apk/dev/debug"
    FASTLANE_LANE: "android_dev_debug"

###########################################################################
# DEV RELEASE
###########################################################################

build_android_dev_release:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: DevRelease
    GRADLE_TASK: ":android:assembleDevRelease"
    ARTIFACT_DIRECTORY: "android/build/outputs/apk/dev/release"
    FASTLANE_LANE: "android_dev_release"

###########################################################################
# PROD DEBUG
###########################################################################

build_android_prod_debug:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: ProdDebug
    GRADLE_TASK: ":android:assembleProdDebug"
    ARTIFACT_DIRECTORY: "android/build/outputs/apk/prod/debug"
    FASTLANE_LANE: "android_prod_debug"

###########################################################################
# PROD RELEASE
###########################################################################

build_android_prod_release:
  extends:
    - .android_build
    - .master_branch_manual

  variables:
    BUILD_VARIANT: ProdRelease
    GRADLE_TASK: ":android:bundleProdRelease"
    ARTIFACT_DIRECTORY: "android/build/outputs/bundle/prodRelease"
    FASTLANE_LANE: "android_prod_release"
