###########################################################################
# COMMON SETUP
###########################################################################

.common_setup:

  before_script:

    - chmod +x gradlew

    # Install Ruby dependencies
    - bundle config set path "$BUNDLE_PATH"
    - bundle install

###########################################################################
# ANDROID SETUP
###########################################################################

.android_setup:

  extends:
    - .common_setup

  before_script:

    - !reference [.common_setup, before_script]

    - export ANDROID_HOME=$HOME/Library/Android/sdk
    - export ANDROID_SDK_ROOT=$ANDROID_HOME

    - export PATH=$PATH:$ANDROID_HOME/platform-tools
    - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

    # google-services.json
    - |
      echo "$GCP_SERVICE_JSON_ANDROID" | base64 --decode > android/google-services.json

    # Release keystore
    - mkdir -p signingConfig

    - |
      echo "$KEYSTORE_BASE64" | base64 --decode > signingConfig/file.jks

    # keystore.properties
    - |
      cat > keystore.properties <<EOF
      storePassword=$KEYSTORE_PASSWORD
      keyAlias=$KEY_ALIAS
      keyPassword=$KEY_PASSWORD
      EOF

###########################################################################
# IOS SETUP
###########################################################################

.ios_setup:

  extends:
    - .common_setup

  before_script:

    - !reference [.common_setup, before_script]

    - xcodebuild -version

    # Firebase plist

    - |
      echo "$GCP_SERVICE_JSON_IOS" | base64 --decode > ios/GoogleService-Info.plist
      
      # App Store Connect API Key
    - |
      echo "$APP_STORE_CONNECT_API_KEY" | base64 --decode > AuthKey.p8

    # Certificate

    - |
      echo "$IOS_CERTIFICATE_BASE64" \
      | base64 --decode \
      > certificate.p12

    # Provisioning Profile

    - |
      mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

      echo "$IOS_DEV_PROVISIONING_PROFILE_BASE64" \
      | base64 --decode \
      > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    # Keychain

    - |
      security create-keychain \
        -p "$KEYCHAIN_PASSWORD" \
        build.keychain

      security default-keychain \
        -s build.keychain

      security unlock-keychain \
        -p "$KEYCHAIN_PASSWORD" \
        build.keychain

      security import certificate.p12 \
        -k build.keychain \
        -P "$IOS_CERTIFICATE_PASSWORD" \
        -T /usr/bin/codesign

      security set-key-partition-list \
        -S apple-tool:,apple:,codesign: \
        -s \
        -k "$KEYCHAIN_PASSWORD" \
        build.keychain


###########################################################################
# ANDROID BUILD TEMPLATE
###########################################################################

.android_build:

  extends:
    - .android_setup

  stage: deploy

  tags:
    - macos

  script:
    - |
      echo "======================================"
      echo "Building $BUILD_VARIANT"
      echo "======================================"

      chmod +x gradlew

      ./gradlew "$GRADLE_TASK" --no-daemon --warning-mode none

      ARTIFACT=$(find "$ARTIFACT_DIRECTORY" -type f \( -name "*.apk" -o -name "*.aab" \) | head -1)

      if [ -z "$ARTIFACT" ]; then
        echo "Artifact not found!"
        exit 1
      fi

      export ARTIFACT_PATH="$ARTIFACT"

      echo "FIREBASE_ANDROID_APP_ID=$FIREBASE_ANDROID_APP_ID"
      echo "ARTIFACT_PATH=$ARTIFACT_PATH"
      ls -lh "$ARTIFACT_PATH"
      
      echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 --decode > firebase.json
  
      echo "===== CLIENT EMAIL ====="
      cat firebase.json | grep client_email
      
      echo "===== PROJECT ====="
      cat firebase.json | grep project_id
  
      bundle exec fastlane "$FASTLANE_LANE"
        

###########################################################################
# IOS BUILD TEMPLATE
###########################################################################

.ios_build:

  extends:
    - .ios_setup

  stage: deploy

  tags:
    - macos

  script:

    - echo "Building iOS $BUILD_VARIANT"

    - bundle exec fastlane "$FASTLANE_LANE"

  artifacts:

    expire_in: 7 days

    paths:
      - ios/build/


